language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t marshneel/dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true marshneel/dockerreact npm run test -- --coverage
